@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYnJAYWJyLmNvbSIsImlhdCI6MTc0NzgzOTMyMCwiZXhwIjoxNzQ3ODM5MzUwfQ.EKRWGh42ry79a_FdhQjNul1Yk_Vm0ceoFNFp1FMlNrU
GET http://localhost:5000/notes

###
GET http://localhost:5000/token
###

DELETE http://localhost:5000/logout
###


GET http://localhost:5000/notes-auth
Authorization: Bearer {{token}}


###

GET http://localhost:5000/users

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "fzz@fzz.com",
    "password": "12345"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "abr@abr.com",
    "password": "12345"
}
###

GET http://localhost:5000/notes-auth
Authorization: Bearer {{token}}

###
POST http://localhost:5000/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "wle wle cloud gimang",
    "email": "rubychaannn",
    "title": "hayyyyy",
    "category": "nanigasukii"
}

### 

PUT http://localhost:5000/notes/13
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Faiz efendi cloud",
    "email": "fz@gmail.com",
    "title": "buku kematian",
    "category": "nanigasukii"
}

###

DELETE http://localhost:5000/notes/13
Authorization: Bearer {{token}}



###
GET http://localhost:5000/token


###
DELETE https://t7-tcc-be-713031961242.asia-southeast2.run.app/logout

###

GET https://t7-tcc-be-713031961242.asia-southeast2.run.app/notes
###

GET https://t7-tcc-be-713031961242.asia-southeast2.run.app/users
###
GET https://t7-tcc-be-713031961242.asia-southeast2.run.app/token
###
GET https://t7-tcc-be-713031961242.asia-southeast2.run.app/users:2

###
POST https://t7-tcc-be-713031961242.asia-southeast2.run.app/login
Content-Type: application/json

{  
    "email": "abr@abr.com",
    "password": "12345"
}