@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhYnJAZ21haWwuY29tIiwiaWF0IjoxNzQ3NzIzNzY4LCJleHAiOjE3NDc3MjM3OTh9.BWtYhjkZOYI_ULx-HCeVkPt-rixC4AcNByDbi8zzzLw
###

GET http://localhost:5000/users

###

GET http://localhost:5000/users-auth
Authorization: Bearer {{token}}

###

POST http://localhost:5000/register-user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "abr",
    "password": "testing",
    "email": "abr@gmail.com",
    "title": "test tittle",
    "category": "null"
}

### 

PUT http://localhost:5000/update-user/25
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "abraar jihaad",
    "email": "abr@abr.com",
}

###

DELETE http://localhost:5000/delete-user/5
Authorization: Bearer {{token}}


###

POST http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "abr@gmail.com",
    "password": "testing"
}

###
GET http://localhost:5000/token

###

DELETE http://localhost:5000/logout